uploads = []

[[generated]]
id = "7gr3TwHoRQZ0tzXpS6FHJ"
uri = "file://artifacts/3d-game/public/shark-warrior-run1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rM1UibLRUkr4i6UXb2VE8"
uri = "file://artifacts/3d-game/public/shark-warrior-run2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ge38m6rR5cBTK2ITP7vLG"
uri = "file://artifacts/3d-game/public/shark-warrior-jump.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "9Iw9Rq_rMulXywZFtIxut"
uri = "file://artifacts/3d-game/public/assets/icon-512.png"
type = "image"
title = "Icône Google Play — 512×512 PNG"

[[outputs]]
id = "rYWjCaTc3NJRpNLZwEIGw"
uri = "file://artifacts/3d-game/public/assets/icon-1024.png"
type = "image"
title = "Icône App Store — 1024×1024 PNG"
